kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.2363
    roll: 0
    pitch: 0
    yaw: 0
  upper_arm:
    x: 0
    y: 0
    z: 0
    roll: 1.570796327
    pitch: 0
    yaw: 0
  forearm:
    x: -0.862
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  wrist_1:
    x: -0.7287
    y: 0
    z: 0.201
    roll: 0
    pitch: 0
    yaw: 0
  wrist_2:
    x: 0
    y: -0.1593
    z: 0
    roll: 1.570796327
    pitch: 0
    yaw: 0
  wrist_3:
    x: 0
    y: 0.11655
    z: 0
    roll: 1.570796326589793
    pitch: 3.141592653589793
    yaw: 3.141592653589793
  hash: calib_1935737212149401527